services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8899}:${PORT:-8899}"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - .env